from pydantic import BaseModel, Field
from typing import Optional, List

class ProductSchema(BaseModel):
    """Schema representing an enriched product record returned by the API."""

    product_id: str = Field(..., description="Unique identifier of the product (parent_asin)")
    title: str = Field(..., description="Original product title")
    category: Optional[str] = Field(None, description="Primary category of the product")
    gender: Optional[str] = Field(None, description="Target gender (men, women, kids, unisex)")
    color: Optional[str] = Field(None, description="Primary color if a single color can be identified")
    colors: Optional[List[str]] = Field(
        None, description="List of all colors extracted for the product"
    )
    style: Optional[List[str]] = Field(
        None, description="List of style tags (e.g., casual, formal)"
    )
    size: Optional[str] = Field(None, description="Size information when available")
    quantity: Optional[int] = Field(
        None, description="Numeric quantity extracted from the title (e.g., 5 in '5 pairs')"
    )
    quantity_unit: Optional[str] = Field(
        None, description="Unit associated with quantity (pairs, pcs, pack, set)"
    )
    average_rating: Optional[float] = Field(
        None, description="Average star rating for the product"
    )
    rating_number: Optional[int] = Field(
        None, description="Number of ratings the product received"
    )
    image_url: Optional[str] = Field(None, description="URL of the primary product image")
    review_highlights: Optional[str] = Field(
        None, description="Short summary of customer feedback (generated by LLM)"
    )
    review_count: Optional[int] = Field(
        None, description="Total number of usable reviews aggregated for the product"
    )
    # Additional metadata fields can be added later without breaking compatibility
